/**
 * App icon set — Phosphor Icons (MIT, phosphoricons.com), exposed under the names the codebase already uses.
 * Feature icons use the duotone weight; controls (arrows, chevrons, close…) stay regular. Generated by .dev/gen-icons.mjs.
 */
import * as React from "react";
import type { Icon as PhosphorIcon, IconWeight } from "@phosphor-icons/react";
import { BrandIcon } from "@/components/brand/social-icons";
import {
  Alarm as PhAlarm,
  Archive as PhArchive,
  ArrowClockwise as PhArrowClockwise,
  ArrowCounterClockwise as PhArrowCounterClockwise,
  ArrowDown as PhArrowDown,
  ArrowElbowDownLeft as PhArrowElbowDownLeft,
  ArrowLeft as PhArrowLeft,
  ArrowRight as PhArrowRight,
  ArrowSquareOut as PhArrowSquareOut,
  ArrowUUpLeft as PhArrowUUpLeft,
  ArrowUp as PhArrowUp,
  ArrowUpRight as PhArrowUpRight,
  ArrowsClockwise as PhArrowsClockwise,
  ArrowsIn as PhArrowsIn,
  Bank as PhBank,
  Barbell as PhBarbell,
  Bicycle as PhBicycle,
  BookOpenText as PhBookOpenText,
  BowlFood as PhBowlFood,
  Buildings as PhBuildings,
  Cake as PhCake,
  CalendarBlank as PhCalendarBlank,
  CalendarDots as PhCalendarDots,
  Camera as PhCamera,
  CarSimple as PhCarSimple,
  CaretDown as PhCaretDown,
  CaretLeft as PhCaretLeft,
  CaretRight as PhCaretRight,
  CaretUp as PhCaretUp,
  CaretUpDown as PhCaretUpDown,
  ChartBar as PhChartBar,
  ChatCircle as PhChatCircle,
  Check as PhCheck,
  CheckCircle as PhCheckCircle,
  Checks as PhChecks,
  Circle as PhCircle,
  CircleNotch as PhCircleNotch,
  Clock as PhClock,
  Compass as PhCompass,
  Copy as PhCopy,
  CornersOut as PhCornersOut,
  Cpu as PhCpu,
  CreditCard as PhCreditCard,
  CurrencyInr as PhCurrencyInr,
  DotsSixVertical as PhDotsSixVertical,
  DotsThree as PhDotsThree,
  DownloadSimple as PhDownloadSimple,
  Drop as PhDrop,
  EnvelopeSimple as PhEnvelopeSimple,
  Eye as PhEye,
  EyeSlash as PhEyeSlash,
  FastForward as PhFastForward,
  FileText as PhFileText,
  Fingerprint as PhFingerprint,
  Fire as PhFire,
  FlowArrow as PhFlowArrow,
  Footprints as PhFootprints,
  Funnel as PhFunnel,
  Gear as PhGear,
  GearSix as PhGearSix,
  GenderFemale as PhGenderFemale,
  Globe as PhGlobe,
  HandTap as PhHandTap,
  HardDrives as PhHardDrives,
  Heartbeat as PhHeartbeat,
  House as PhHouse,
  ImageSquare as PhImageSquare,
  Info as PhInfo,
  Invoice as PhInvoice,
  Key as PhKey,
  Keyboard as PhKeyboard,
  Lifebuoy as PhLifebuoy,
  Lightbulb as PhLightbulb,
  Lightning as PhLightning,
  Link as PhLink,
  List as PhList,
  Lock as PhLock,
  LockKey as PhLockKey,
  MagnifyingGlass as PhMagnifyingGlass,
  MapPin as PhMapPin,
  Money as PhMoney,
  Monitor as PhMonitor,
  Moon as PhMoon,
  MusicNotes as PhMusicNotes,
  Palette as PhPalette,
  PaperPlaneTilt as PhPaperPlaneTilt,
  PauseCircle as PhPauseCircle,
  PencilSimple as PhPencilSimple,
  Percent as PhPercent,
  PersonSimple as PhPersonSimple,
  Phone as PhPhone,
  Play as PhPlay,
  PlugsConnected as PhPlugsConnected,
  Plus as PhPlus,
  Power as PhPower,
  Printer as PhPrinter,
  Prohibit as PhProhibit,
  Pulse as PhPulse,
  QrCode as PhQrCode,
  Question as PhQuestion,
  Receipt as PhReceipt,
  Scales as PhScales,
  Scan as PhScan,
  ScanSmiley as PhScanSmiley,
  SealCheck as PhSealCheck,
  SecurityCamera as PhSecurityCamera,
  Shield as PhShield,
  ShieldCheck as PhShieldCheck,
  ShieldWarning as PhShieldWarning,
  Shower as PhShower,
  SidebarSimple as PhSidebarSimple,
  SignOut as PhSignOut,
  SkipForward as PhSkipForward,
  Snowflake as PhSnowflake,
  Sparkle as PhSparkle,
  SpeakerHigh as PhSpeakerHigh,
  SquaresFour as PhSquaresFour,
  Stack as PhStack,
  Star as PhStar,
  Sun as PhSun,
  SunDim as PhSunDim,
  Sunglasses as PhSunglasses,
  Sword as PhSword,
  Target as PhTarget,
  Ticket as PhTicket,
  Timer as PhTimer,
  Trash as PhTrash,
  Tray as PhTray,
  TrendUp as PhTrendUp,
  Trophy as PhTrophy,
  UploadSimple as PhUploadSimple,
  User as PhUser,
  UserCheck as PhUserCheck,
  UserGear as PhUserGear,
  UserPlus as PhUserPlus,
  Users as PhUsers,
  Wallet as PhWallet,
  Warning as PhWarning,
  WarningCircle as PhWarningCircle,
  Waves as PhWaves,
  Webcam as PhWebcam,
  WifiHigh as PhWifiHigh,
  Wind as PhWind,
  X as PhX,
  XCircle as PhXCircle,
} from "@phosphor-icons/react/dist/ssr";

export type IconProps = Omit<React.ComponentProps<"svg">, "ref"> & {
  size?: number | string;
  weight?: IconWeight;
  mirrored?: boolean;
  /** accepted for compatibility; Phosphor icons are filled shapes */
  strokeWidth?: number | string;
};
export type IconComponent = React.ComponentType<IconProps> & { displayName?: string };

function icon(Ph: PhosphorIcon, name: string, weight: IconWeight): IconComponent {
  const I = ({ strokeWidth: _s, weight: w, ...props }: IconProps) => {
    void _s;
    return <Ph weight={w ?? weight} {...props} />;
  };
  I.displayName = name;
  return I;
}

export const Activity = icon(PhPulse, "Activity", "duotone");
export const AirVent = icon(PhWind, "AirVent", "duotone");
export const AlarmClock = icon(PhAlarm, "AlarmClock", "duotone");
export const Apple = icon(PhBowlFood, "Apple", "duotone");
export const Archive = icon(PhArchive, "Archive", "duotone");
export const ArrowDown = icon(PhArrowDown, "ArrowDown", "regular");
export const ArrowLeft = icon(PhArrowLeft, "ArrowLeft", "regular");
export const ArrowRight = icon(PhArrowRight, "ArrowRight", "regular");
export const ArrowUp = icon(PhArrowUp, "ArrowUp", "regular");
export const ArrowUpRight = icon(PhArrowUpRight, "ArrowUpRight", "regular");
export const BadgeCheck = icon(PhSealCheck, "BadgeCheck", "fill");
export const Banknote = icon(PhMoney, "Banknote", "duotone");
export const BicepsFlexed = icon(PhBarbell, "BicepsFlexed", "duotone");
export const Bike = icon(PhBicycle, "Bike", "duotone");
export const Building2 = icon(PhBuildings, "Building2", "duotone");
export const Cake = icon(PhCake, "Cake", "duotone");
export const CalendarClock = icon(PhCalendarDots, "CalendarClock", "duotone");
export const CalendarDays = icon(PhCalendarBlank, "CalendarDays", "duotone");
export const Cctv = icon(PhSecurityCamera, "Cctv", "duotone");
export const ChartColumn = icon(PhChartBar, "ChartColumn", "duotone");
export const Check = icon(PhCheck, "Check", "bold");
export const CheckIcon = icon(PhCheck, "CheckIcon", "bold");
export const CheckCheck = icon(PhChecks, "CheckCheck", "bold");
export const ChevronDown = icon(PhCaretDown, "ChevronDown", "regular");
export const ChevronDownIcon = icon(PhCaretDown, "ChevronDownIcon", "regular");
export const ChevronLeft = icon(PhCaretLeft, "ChevronLeft", "regular");
export const ChevronRight = icon(PhCaretRight, "ChevronRight", "regular");
export const ChevronRightIcon = icon(PhCaretRight, "ChevronRightIcon", "regular");
export const ChevronUpIcon = icon(PhCaretUp, "ChevronUpIcon", "regular");
export const ChevronsUpDown = icon(PhCaretUpDown, "ChevronsUpDown", "regular");
export const CircleAlert = icon(PhWarningCircle, "CircleAlert", "duotone");
export const CircleCheck = icon(PhCheckCircle, "CircleCheck", "duotone");
export const CircleCheckIcon = icon(PhCheckCircle, "CircleCheckIcon", "duotone");
export const CircleHelp = icon(PhQuestion, "CircleHelp", "duotone");
export const CircleX = icon(PhXCircle, "CircleX", "duotone");
export const Clock = icon(PhClock, "Clock", "duotone");
export const Compass = icon(PhCompass, "Compass", "duotone");
export const Copy = icon(PhCopy, "Copy", "regular");
export const CornerDownLeft = icon(PhArrowElbowDownLeft, "CornerDownLeft", "regular");
export const CreditCard = icon(PhCreditCard, "CreditCard", "duotone");
export const Download = icon(PhDownloadSimple, "Download", "regular");
export const Droplets = icon(PhDrop, "Droplets", "duotone");
export const Dumbbell = icon(PhBarbell, "Dumbbell", "duotone");
export const ExternalLink = icon(PhArrowSquareOut, "ExternalLink", "regular");
export const Eye = icon(PhEye, "Eye", "regular");
export const EyeOff = icon(PhEyeSlash, "EyeOff", "regular");
export const FileText = icon(PhFileText, "FileText", "duotone");
export const Flame = icon(PhFire, "Flame", "duotone");
export const Footprints = icon(PhFootprints, "Footprints", "duotone");
export const GlassWater = icon(PhDrop, "GlassWater", "duotone");
export const Globe = icon(PhGlobe, "Globe", "duotone");
export const GripVertical = icon(PhDotsSixVertical, "GripVertical", "regular");
export const HeartPulse = icon(PhHeartbeat, "HeartPulse", "duotone");
export const House = icon(PhHouse, "House", "duotone");
export const ImagePlus = icon(PhImageSquare, "ImagePlus", "duotone");
export const Inbox = icon(PhTray, "Inbox", "duotone");
export const IndianRupee = icon(PhCurrencyInr, "IndianRupee", "duotone");
export const InfoIcon = icon(PhInfo, "InfoIcon", "duotone");
export const KeyRound = icon(PhKey, "KeyRound", "duotone");
export const Keyboard = icon(PhKeyboard, "Keyboard", "duotone");
export const Landmark = icon(PhBank, "Landmark", "duotone");
export const Layers = icon(PhStack, "Layers", "duotone");
export const LayoutDashboard = icon(PhSquaresFour, "LayoutDashboard", "duotone");
export const LifeBuoy = icon(PhLifebuoy, "LifeBuoy", "duotone");
export const Link = icon(PhLink, "Link", "regular");
export const Loader2 = icon(PhCircleNotch, "Loader2", "bold");
export const Loader2Icon = icon(PhCircleNotch, "Loader2Icon", "bold");
export const Lock = icon(PhLock, "Lock", "duotone");
export const LockKeyhole = icon(PhLockKey, "LockKeyhole", "duotone");
export const LogOut = icon(PhSignOut, "LogOut", "duotone");
export const Mail = icon(PhEnvelopeSimple, "Mail", "duotone");
export const MapPin = icon(PhMapPin, "MapPin", "duotone");
export const Menu = icon(PhList, "Menu", "regular");
export const MessageCircle = icon(PhChatCircle, "MessageCircle", "duotone");
export const Monitor = icon(PhMonitor, "Monitor", "duotone");
export const Moon = icon(PhMoon, "Moon", "duotone");
export const MoreHorizontal = icon(PhDotsThree, "MoreHorizontal", "bold");
export const Music = icon(PhMusicNotes, "Music", "duotone");
export const OctagonXIcon = icon(PhProhibit, "OctagonXIcon", "duotone");
export const Palette = icon(PhPalette, "Palette", "duotone");
export const PanelLeft = icon(PhSidebarSimple, "PanelLeft", "duotone");
export const PanelLeftClose = icon(PhSidebarSimple, "PanelLeftClose", "duotone");
export const PauseCircle = icon(PhPauseCircle, "PauseCircle", "duotone");
export const Pencil = icon(PhPencilSimple, "Pencil", "duotone");
export const Percent = icon(PhPercent, "Percent", "regular");
export const PersonStanding = icon(PhPersonSimple, "PersonStanding", "duotone");
export const Phone = icon(PhPhone, "Phone", "duotone");
export const Play = icon(PhPlay, "Play", "duotone");
export const Plus = icon(PhPlus, "Plus", "bold");
export const Power = icon(PhPower, "Power", "duotone");
export const Printer = icon(PhPrinter, "Printer", "duotone");
export const QrCode = icon(PhQrCode, "QrCode", "duotone");
export const Receipt = icon(PhReceipt, "Receipt", "duotone");
export const ReceiptText = icon(PhInvoice, "ReceiptText", "duotone");
export const RefreshCw = icon(PhArrowsClockwise, "RefreshCw", "regular");
export const RotateCcw = icon(PhArrowCounterClockwise, "RotateCcw", "regular");
export const RotateCw = icon(PhArrowClockwise, "RotateCw", "regular");
export const Scale = icon(PhScales, "Scale", "duotone");
export const ScanLine = icon(PhScan, "ScanLine", "duotone");
export const Search = icon(PhMagnifyingGlass, "Search", "regular");
export const SearchIcon = icon(PhMagnifyingGlass, "SearchIcon", "regular");
export const Send = icon(PhPaperPlaneTilt, "Send", "duotone");
export const Settings = icon(PhGear, "Settings", "duotone");
export const Settings2 = icon(PhGearSix, "Settings2", "duotone");
export const ShieldAlert = icon(PhShieldWarning, "ShieldAlert", "duotone");
export const ShieldCheck = icon(PhShieldCheck, "ShieldCheck", "duotone");
export const ShieldQuestion = icon(PhShield, "ShieldQuestion", "duotone");
export const ShowerHead = icon(PhShower, "ShowerHead", "duotone");
export const SkipForward = icon(PhSkipForward, "SkipForward", "duotone");
export const Snowflake = icon(PhSnowflake, "Snowflake", "duotone");
export const Sparkles = icon(PhSparkle, "Sparkles", "duotone");
export const SquareParking = icon(PhCarSimple, "SquareParking", "duotone");
export const Star = icon(PhStar, "Star", "duotone");
export const Sun = icon(PhSun, "Sun", "duotone");
export const Swords = icon(PhSword, "Swords", "duotone");
export const Target = icon(PhTarget, "Target", "duotone");
export const Ticket = icon(PhTicket, "Ticket", "duotone");
export const Timer = icon(PhTimer, "Timer", "duotone");
export const Trash2 = icon(PhTrash, "Trash2", "duotone");
export const TrendingUp = icon(PhTrendUp, "TrendingUp", "regular");
export const TriangleAlert = icon(PhWarning, "TriangleAlert", "duotone");
export const TriangleAlertIcon = icon(PhWarning, "TriangleAlertIcon", "duotone");
export const Trophy = icon(PhTrophy, "Trophy", "duotone");
export const Undo2 = icon(PhArrowUUpLeft, "Undo2", "regular");
export const Upload = icon(PhUploadSimple, "Upload", "regular");
export const UserCheck = icon(PhUserCheck, "UserCheck", "duotone");
export const UserCog = icon(PhUserGear, "UserCog", "duotone");
export const UserPlus = icon(PhUserPlus, "UserPlus", "duotone");
export const UserRound = icon(PhUser, "UserRound", "duotone");
export const UsersRound = icon(PhUsers, "UsersRound", "duotone");
export const Venus = icon(PhGenderFemale, "Venus", "duotone");
export const Volume2 = icon(PhSpeakerHigh, "Volume2", "duotone");
export const Wallet = icon(PhWallet, "Wallet", "duotone");
export const Waves = icon(PhWaves, "Waves", "duotone");
export const Wifi = icon(PhWifiHigh, "Wifi", "duotone");
export const Workflow = icon(PhFlowArrow, "Workflow", "duotone");
export const X = icon(PhX, "X", "regular");
export const XIcon = icon(PhX, "XIcon", "regular");
export const Zap = icon(PhLightning, "Zap", "duotone");
export const Fingerprint = icon(PhFingerprint, "Fingerprint", "duotone");
export const ScanFace = icon(PhScanSmiley, "ScanFace", "duotone");
export const Cpu = icon(PhCpu, "Cpu", "duotone");
export const Webcam = icon(PhWebcam, "Webcam", "duotone");
export const Router = icon(PhHardDrives, "Router", "duotone");
export const Plug = icon(PhPlugsConnected, "Plug", "duotone");
export const CircleDot = icon(PhCircle, "CircleDot", "fill");
export const Camera = icon(PhCamera, "Camera", "duotone");
export const Maximize = icon(PhCornersOut, "Maximize", "regular");
export const Info = icon(PhInfo, "Info", "duotone");
export const HandTap = icon(PhHandTap, "HandTap", "duotone");
export const BookOpen = icon(PhBookOpenText, "BookOpen", "duotone");
export const Lightbulb = icon(PhLightbulb, "Lightbulb", "duotone");
export const Funnel = icon(PhFunnel, "Funnel", "regular");
export const ChartBar = icon(PhChartBar, "ChartBar", "duotone");
export const Question = icon(PhQuestion, "Question", "duotone");
export const SkipAhead = icon(PhFastForward, "SkipAhead", "regular");
export const SunDim = icon(PhSunDim, "SunDim", "duotone");
export const Sunglasses = icon(PhSunglasses, "Sunglasses", "duotone");
export const Users = icon(PhUsers, "Users", "duotone");
export const ArrowsIn = icon(PhArrowsIn, "ArrowsIn", "regular");

/** The real WhatsApp mark (Simple Icons) — used wherever the action opens WhatsApp. */
export const WhatsApp: IconComponent = Object.assign(
  ({ strokeWidth: _s, weight: _w, mirrored: _m, size, ...props }: IconProps) => {
    void _s;
    void _w;
    void _m;
    return <BrandIcon width={size ?? "1em"} height={size ?? "1em"} {...props} name="whatsapp" />;
  },
  { displayName: "WhatsApp" },
);
