import {
  Activity,
  AirVent,
  Apple,
  BicepsFlexed,
  Bike,
  Cctv,
  CircleCheck,
  Clock,
  Droplets,
  Dumbbell,
  Flame,
  Footprints,
  GlassWater,
  HeartPulse,
  LockKeyhole,
  Music,
  PersonStanding,
  Scale,
  ShowerHead,
  SquareParking,
  Swords,
  Timer,
  Trophy,
  UserCheck,
  Venus,
  Waves,
  Wifi,
  type LucideIcon,
} from "lucide-react";

/** First match wins, so the more specific words come first. */
const RULES: [RegExp, LucideIcon][] = [
  [/women|ladies|female/i, Venus],
  [/personal|pt\b|coach|trainer|certified/i, UserCheck],
  [/diet|nutrition|meal|supplement/i, Apple],
  [/body ?comp|bmi|inbody|assessment|weigh/i, Scale],
  [/steam|sauna|heat/i, Flame],
  [/shower|bath/i, ShowerHead],
  [/locker|storage|safe/i, LockKeyhole],
  [/park/i, SquareParking],
  [/\bac\b|air.?con|cooled|climate/i, AirVent],
  [/pool|swim/i, Waves],
  [/cycl|spin|bike/i, Bike],
  [/cardio|treadmill|run|elliptical/i, HeartPulse],
  [/yoga|stretch|mobility|pilates|flex/i, PersonStanding],
  [/zumba|dance|aerobic|music/i, Music],
  [/box|mma|martial|kick/i, Swords],
  [/crossfit|functional|hiit|circuit|metcon/i, Timer],
  [/strength|power|olympic|barbell|rack|platform/i, BicepsFlexed],
  [/weight|dumbbell|machine|equipment/i, Dumbbell],
  [/turf|sled|track|walk/i, Footprints],
  [/water|hydration|drink/i, GlassWater],
  [/wifi|wi-fi|internet/i, Wifi],
  [/cctv|security|camera/i, Cctv],
  [/24|hour|early|late|open/i, Clock],
  [/compet|event|challenge|transform/i, Trophy],
  [/physio|rehab|recovery|massage/i, Activity],
  [/clean|hygien|sanit/i, Droplets],
];

export function amenityIcon(label: string): LucideIcon {
  return RULES.find(([pattern]) => pattern.test(label))?.[1] ?? CircleCheck;
}
